#!/usr/bin/env bun
/** MCP server for Usagi/Tsuki plugin engineering. */
import { McpServer } from "@modelcontextprotocol/sdk/server/mcp.js";
import { StdioServerTransport } from "@modelcontextprotocol/sdk/server/stdio.js";
import { z } from "zod";
import { readFileSync, existsSync, mkdirSync, writeFileSync, readdirSync, statSync } from "fs";
import { join, resolve, dirname, relative, extname, basename } from "path";
import { execFile } from "child_process";
import { promisify } from "util";

const execFileAsync = promisify(execFile);
const ROOT = dirname(new URL(import.meta.url).pathname);
const DOC_CANDIDATES = [join(ROOT, "docs"), join(ROOT, "skill", "references")];
const DEFAULT_ALLOWED_HOSTS = new Set(["github.com", "raw.githubusercontent.com", "jitpack.io"]);
const VERSION = "0.2.0";
const MAX_FILE_BYTES = 2_000_000;
type RecordValue = Record<string, unknown>;
type ToolResult = { content: [{ type: "text"; text: string }] };

function result(value: unknown): ToolResult { return { content: [{ type: "text", text: JSON.stringify(value, null, 2) }] }; }
function fail(error: string, extra: RecordValue = {}): ToolResult { return result({ ok: false, error, ...extra }); }
function text(path: string): string { try { return existsSync(path) && statSync(path).size <= MAX_FILE_BYTES ? readFileSync(path, "utf8") : ""; } catch { return ""; } }
function safePath(path: string): string { const value = resolve(path); if (value.includes("\0")) throw new Error("Invalid path"); return value; }
function files(root: string, extensions: Set<string>, max = 500): string[] {
  const output: string[] = [];
  function walk(dir: string) {
    if (output.length >= max) return;
    let entries: string[]; try { entries = readdirSync(dir); } catch { return; }
    for (const entry of entries) {
      if (output.length >= max || [".git", ".gradle", "node_modules", "build", "dist"].includes(entry)) continue;
      const full = join(dir, entry); try { const info = statSync(full); if (info.isDirectory()) walk(full); else if (extensions.has(extname(full).toLowerCase())) output.push(full); } catch {}
    }
  }
  walk(root); return output;
}
function doc(names: string[]): string { for (const dir of DOC_CANDIDATES) for (const name of names) { const value = text(join(dir, name)); if (value) return value; } return ""; }
function publicHttps(url: string): boolean { try { const u = new URL(url); return u.protocol === "https:" && !u.username && !u.password && !["localhost", "127.0.0.1", "::1", "0.0.0.0"].includes(u.hostname); } catch { return false; } }
function allowed(url: string, extra: string[] = []): boolean { try { const host = new URL(url).hostname.toLowerCase(); const hosts = new Set([...DEFAULT_ALLOWED_HOSTS, ...extra.map((x) => x.toLowerCase())]); return publicHttps(url) && ([...hosts].some((x) => host === x || host.endsWith(`.${x}`))); } catch { return false; } }
async function fetchPublic(url: string, extra: string[] = []): Promise<RecordValue> { if (!allowed(url, extra)) return { ok: false, error: "URL must be public HTTPS and its host must be in the safe allowlist", url }; try { const response = await fetch(url, { headers: { "User-Agent": "tsuki-plugin-engineering/0.2" }, signal: AbortSignal.timeout(20000) }); const body = await response.text(); return { ok: response.ok, status: response.status, url, content_type: response.headers.get("content-type"), text: body.slice(0, MAX_FILE_BYTES) }; } catch (error) { return { ok: false, error: String(error), url }; } }
function writeReport(path: string, body: string): string { const output = safePath(path); mkdirSync(dirname(output), { recursive: true }); writeFileSync(output, body, "utf8"); return output; }
const PAYWALL_SIGNALS = /subscri(be|ption)|premium|paywall|unlock\s+with|coins?\b|tickets?\b|credits?\b|buy\s+(this\s+)?chapter|purchase|pay[\s-]?per|early\s+access|vip\s+(only|access|chapter)|membership/i;
const LOGIN_WALL_SIGNALS = /sign\s?in\s+to\s+(continue|read|view)|log\s?in\s+to\s+(continue|read|view)|create\s+(a\s+)?free\s+account|members?\s+only|please\s+log\s?in|authentication\s+required/i;
const LOGIN_REDIRECT_SIGNALS = /\/(login|signin|sign-in|account\/login)(?:[/?]|$)/i;
async function classifyOneCapability(url: string, allow_hosts: string[]): Promise<RecordValue> {
  const evidence: string[] = [];
  const fetched = await fetchPublic(url, allow_hosts);
  if (fetched.ok === false) {
    const status = typeof fetched.status === "number" ? fetched.status : null;
    if (status === 401 || status === 403) evidence.push(`Anonymous request returned HTTP ${status}`);
    else evidence.push(`Anonymous request failed: ${String(fetched.error ?? `HTTP ${status ?? "unknown"}`)}`);
    return { url, verdict: "authenticated", confidence: "low", evidence, note: "Anonymous fetch did not succeed; could also be blocked-by-terms or a transient error. Verify manually before concluding this capability is buildable." };
  }
  const body = String(fetched.text ?? "");
  const finalUrl = String(fetched.url ?? url);
  const paywallMatch = body.match(PAYWALL_SIGNALS);
  if (paywallMatch) { evidence.push(`Response body contains a payment/subscription signal: "${paywallMatch[0]}"`); return { url, verdict: "paywalled", confidence: "medium", evidence, note: "Treat as permanently out of scope. Do not implement login, payment, or cookie passthrough for this capability." }; }
  if (LOGIN_REDIRECT_SIGNALS.test(finalUrl) && finalUrl !== url) { evidence.push(`Anonymous request was redirected to a login-shaped URL: ${finalUrl}`); return { url, verdict: "authenticated", confidence: "medium", evidence, note: "Do not implement login or session capture. Treat as blocked unless a separate anonymous path exists for this capability." }; }
  const loginWallMatch = body.match(LOGIN_WALL_SIGNALS);
  if (loginWallMatch) { evidence.push(`Response body contains a login-wall signal: "${loginWallMatch[0]}"`); return { url, verdict: "authenticated", confidence: "medium", evidence, note: "Do not implement login or session capture. Treat as blocked unless a separate anonymous path exists for this capability." }; }
  evidence.push(`Anonymous request succeeded (HTTP ${fetched.status}) with no payment or login-wall signal detected in the response body`);
  return { url, verdict: "public", confidence: "medium", evidence, note: "Automated signal only. Still confirm terms of service and robots.txt separately — this check cannot see ToS text that is not on the fetched page." };
}
async function classifyAccess(capabilities: { name: string; url: string }[], allow_hosts: string[]): Promise<RecordValue> {
  const results: RecordValue[] = [];
  for (const capability of capabilities.slice(0, 10)) results.push({ capability: capability.name, ...(await classifyOneCapability(capability.url, allow_hosts)) });
  const verdicts = results.map((x) => String(x.verdict));
  const buildable = results.filter((x) => x.verdict === "public").map((x) => x.capability);
  const excluded = results.filter((x) => x.verdict !== "public").map((x) => ({ capability: x.capability, verdict: x.verdict }));
  return {
    ok: true,
    results,
    summary: { public: verdicts.filter((v) => v === "public").length, authenticated: verdicts.filter((v) => v === "authenticated").length, paywalled: verdicts.filter((v) => v === "paywalled").length },
    buildable_capabilities: buildable,
    excluded_capabilities: excluded,
    reminder: "This is an automated first pass only (see references/access-classification.md). Low-confidence or ambiguous results must be reviewed manually, and terms of service / robots.txt must still be checked explicitly \u2014 this tool cannot read policy documents that are not on the fetched page itself. Never implement login, session capture, token minting, or a user-supplied paid-session cookie for a capability classified authenticated or paywalled, regardless of confidence level."
  };
}
function commandExists(command: string): boolean {
  const pathValue = process.env.PATH ?? "";
  const suffixes = process.platform === "win32" ? ["", ".exe", ".cmd", ".bat"] : [""];
  return pathValue.split(process.platform === "win32" ? ";" : ":").some((dir) => suffixes.some((suffix) => existsSync(join(dir, `${command}${suffix}`))));
}
async function run(command: string, args: string[], cwd: string, timeout = 120000): Promise<RecordValue> { try { const value = await execFileAsync(command, args, { cwd, timeout, maxBuffer: 2_000_000, windowsHide: true }); return { ok: true, command: [command, ...args].join(" "), stdout: value.stdout, stderr: value.stderr }; } catch (error: any) { return { ok: false, command: [command, ...args].join(" "), stdout: error.stdout ?? "", stderr: error.stderr ?? String(error), exit_code: error.code ?? null }; } }
function jsonFile(path: string): unknown { return JSON.parse(readFileSync(path, "utf8")); }
function strings(value: unknown, output: string[] = []): string[] { if (typeof value === "string") output.push(value); else if (Array.isArray(value)) value.forEach((x) => strings(x, output)); else if (value && typeof value === "object") Object.values(value as RecordValue).forEach((x) => strings(x, output)); return output; }
function paths(value: unknown, prefix = "$", output: string[] = []): string[] { if (output.length >= 300) return output; if (Array.isArray(value)) { if (value.length) paths(value[0], `${prefix}[0]`, output); } else if (value && typeof value === "object") for (const [key, child] of Object.entries(value as RecordValue)) { const path = `${prefix}.${key}`; output.push(path); paths(child, path, output); } return output; }
function chapterNumber(value: string): number | null { const match = value.match(/(?:chapter|ch\.?|episode|ep\.?|第)\s*([0-9]+(?:\.[0-9]+)?)/i) ?? value.match(/(?:^|\s)([0-9]+(?:\.[0-9]+)?)(?:\s|$)/); return match ? Number(match[1]) : null; }
function normalize(input: unknown): { chapters: RecordValue[]; removed: RecordValue[]; warnings: string[] } {
  const chapters: RecordValue[] = [], removed: RecordValue[] = [], warnings: string[] = [], seen = new Set<string>();
  for (const item of Array.isArray(input) ? input : []) {
    const record: RecordValue = typeof item === "string" ? { title: item, url: item } : item && typeof item === "object" ? { ...(item as RecordValue) } : {};
    const title = String(record.title ?? record.name ?? record.chapter ?? ""), url = String(record.url ?? record.link ?? ""), lower = `${title} ${url}`.toLowerCase();
    if (/read\s+(from\s+beginning|latest)|bookmark|advert|recommend|next\s+chapter|previous\s+chapter/.test(lower)) { removed.push({ ...record, reason: "navigation_or_non_chapter" }); continue; }
    const key = url || `${title}|${record.number ?? ""}`; if (key && seen.has(key)) { removed.push({ ...record, reason: "duplicate" }); continue; } if (key) seen.add(key);
    const number = typeof record.number === "number" ? record.number : chapterNumber(title); if (number !== null) record.number = number; else warnings.push(`Could not determine a chapter number for ${title || url}`); chapters.push(record);
  }
  chapters.sort((a, b) => { const an = typeof a.number === "number" ? a.number : Infinity, bn = typeof b.number === "number" ? b.number : Infinity; return an - bn || String(a.title ?? a.url ?? "").localeCompare(String(b.title ?? b.url ?? "")); }); return { chapters, removed, warnings };
}
function extractPageCandidates(source: string): RecordValue[] {
  const candidates: RecordValue[] = [];
  const seen = new Set<string>();
  const add = (url: string, index?: number, attribute?: string) => {
    const clean = url.replace(/&amp;/g, "&").trim();
    if (!clean || /^(data:|javascript:|#)/i.test(clean) || seen.has(clean)) return;
    seen.add(clean); candidates.push({ url: clean, ...(index !== undefined ? { index } : {}), ...(attribute ? { attribute } : {}) });
  };
  for (const match of source.matchAll(/(?:data-src|data-original|data-lazy-src|data-url|src)=["']([^"']+)["']/gi)) add(match[1], undefined, match[0].split("=")[0]);
  for (const match of source.matchAll(/srcset=["']([^"']+)["']/gi)) for (const entry of match[1].split(",")) add(entry.trim().split(/\s+/)[0], undefined, "srcset");
  for (const match of source.matchAll(/(?:page|pageNumber|page_number|index|order)["'\s:=]+([0-9]{1,5})[^\n]{0,200}?(?:url|src|image)["'\s:=]+["']([^"']+)["']/gi)) add(match[2], Number(match[1]), "embedded-index");
  return candidates.map((item, position) => ({ ...item, position }));
}
async function validatePageRecords(input: unknown, expectedCount?: number): Promise<RecordValue> {
  const records = Array.isArray(input) ? input : [];
  const pages: RecordValue[] = records.map((item, position) => typeof item === "string" ? { url: item, position } : { ...(item as RecordValue), position });
  const invalidUrls: RecordValue[] = [], duplicateUrls: string[] = [], placeholders: RecordValue[] = [], seen = new Set<string>();
  for (const page of pages) {
    const url = String(page.url ?? page.src ?? "");
    if (!publicHttps(url)) invalidUrls.push({ ...page, reason: "not_public_https" });
    if (seen.has(url)) duplicateUrls.push(url); else seen.add(url);
    if (/placeholder|loading|blank|advert|logo|avatar|thumbnail/i.test(`${url} ${page.alt ?? ""}`)) placeholders.push({ ...page, reason: "placeholder_or_non_page_pattern" });
  }
  const indexes = pages.map((page) => typeof page.index === "number" ? page.index : null).filter((x): x is number => x !== null);
  const sortedIndexes = [...indexes].sort((a, b) => a - b);
  const missingIndexes: number[] = [];
  if (sortedIndexes.length > 1) for (let index = sortedIndexes[0]; index <= sortedIndexes[sortedIndexes.length - 1]; index++) if (!sortedIndexes.includes(index)) missingIndexes.push(index);
  if (expectedCount !== undefined && pages.length < expectedCount) for (let index = pages.length; index < expectedCount; index++) missingIndexes.push(index);
  const ordering = indexes.length > 1 && indexes.every((value, index) => index === 0 || value >= indexes[index - 1]) ? "ascending" : indexes.length > 1 ? "not_ascending" : "unknown";
  return { ok: invalidUrls.length === 0 && duplicateUrls.length === 0 && placeholders.length === 0 && missingIndexes.length === 0, page_count: pages.length, expected_page_count: expectedCount ?? null, missing_indexes: [...new Set(missingIndexes)], duplicate_urls: [...new Set(duplicateUrls)], invalid_urls: invalidUrls, placeholder_images: placeholders, ordering, warnings: missingIndexes.length ? ["One or more page indexes are missing"] : [] };
}
function inspection(root: string): RecordValue {
  const kt = files(root, new Set([".kt"])); const combined = kt.map(text).join("\n");
  const checks: [RegExp, string][] = [[/Tsuki/, "Tsuki dependency/reference"], [/MangaParser|PagedMangaParser/, "MangaParser reference"], [/getList\s*\(/, "getList"], [/getDetails\s*\(/, "getDetails"], [/getPages\s*\(/, "getPages"], [/getPageUrl\s*\(/, "getPageUrl"], [/getFilterOptions\s*\(/, "getFilterOptions"], [/MangaListFilter/, "filter model/reference"], [/title|name/, "title/name metadata"], [/author|artist/, "author metadata"], [/status/, "status metadata"], [/cover|thumbnail/, "cover or thumbnail metadata"], [/rating/, "rating metadata"], [/sortedBy|sortedWith|compareBy|reversed/, "explicit ordering logic"], [/Read from beginning|Read latest|readFromBeginning|readLatest/, "navigation-entry exclusion"], [/https?:\/\//, "hardcoded URL"], [/decrypt|bypass|captcha|anti.?bot/, "potential bypass logic"]];
  const findings = checks.map(([pattern, message]) => ({ message, present: pattern.test(combined), severity: pattern.test(combined) && ["hardcoded URL", "potential bypass logic"].includes(message) ? "warning" : pattern.test(combined) ? "info" : "warning" }));
  return { files: kt.map((x) => relative(root, x)), findings, metadata_coverage: findings.filter((x) => /metadata/.test(x.message)).map((x) => ({ field: x.message, present: x.present })), filter_coverage: findings.filter((x) => /filter|order/.test(x.message)).map((x) => ({ capability: x.message, present: x.present })) };
}
function resolveSourceFile(nameOrPath: string): { path: string; error?: string } {
  const direct = safePath(nameOrPath);
  if (existsSync(direct) && statSync(direct).isFile()) return { path: direct };
  const searchRoots = [".", "src", "src/main/kotlin"].map((x) => safePath(x)).filter(existsSync);
  const target = nameOrPath.toLowerCase().replace(/\.kt$/, "");
  for (const root of searchRoots) for (const file of files(root, new Set([".kt"]), 2000)) if (basename(file).toLowerCase().replace(/\.kt$/, "") === target) return { path: file };
  return { path: direct, error: `No .kt file found matching "${nameOrPath}". Pass an exact path, or a class/source name that matches a .kt filename under the current directory.` };
}
function extractSourceProfile(source: string): RecordValue {
  const domains = [...new Set([...source.matchAll(/(?:BASE_URL|baseUrl|domain)\s*[=:]\s*"(https?:\/\/[^"]+)"/gi)].map((m) => m[1]))];
  const anyUrls = [...new Set([...source.matchAll(/"(https?:\/\/[^"\s]+)"/g)].map((m) => m[1]))].slice(0, 20);
  const cssSelectors = [...new Set([...source.matchAll(/\.(?:select|selectFirst)\s*\(\s*"([^"]+)"\s*\)/g)].map((m) => m[1]))];
  const attrCalls = [...new Set([...source.matchAll(/\.attr\s*\(\s*"([^"]+)"\s*\)/g)].map((m) => m[1]))];
  const jsonPaths = [...new Set([...source.matchAll(/(?:jsonObject|json|obj)(?:\??)\[\s*"([^"]+)"\s*\]/g), ...source.matchAll(/\.get(?:String|Int|JSONArray|JSONObject)?\s*\(\s*"([^"]+)"\s*\)/g)].map((m) => m[1]))];
  const genreLike = [...new Set([...source.matchAll(/"([A-Z][a-zA-Z\- ]{2,20})"\s*(?:to|,)\s*"?\d/g)].map((m) => m[1]))].slice(0, 40);
  const hasFilters = /MangaListFilter|getFilterOptions|SortOrder/.test(source);
  const hasPagination = /page\s*[:=]|offset\s*[:=]|Pageable|hasNextPage/i.test(source);
  const methods = ["getList", "getDetails", "getPages", "getPageUrl", "getFilterOptions"].filter((name) => new RegExp(`fun\\s+${name}\\s*\\(`).test(source));
  return { canonical_domains: domains, other_urls_seen: anyUrls, css_selectors: cssSelectors, attr_lookups: attrCalls, json_keys: jsonPaths, possible_genre_labels: genreLike, has_filter_support: hasFilters, has_pagination_support: hasPagination, implemented_methods: methods };
}
async function liveTestSource(sourcePath: string, allow_hosts: string[]): Promise<RecordValue> {
  const source = text(sourcePath);
  if (!source) return { ok: false, error: "Could not read source file", path: sourcePath };
  const profile = extractSourceProfile(source);
  const domain = String((profile.canonical_domains as string[])[0] ?? (profile.other_urls_seen as string[])[0] ?? "");
  const checks: RecordValue[] = [];
  if (!domain) { checks.push({ check: "domain_resolution", ok: false, detail: "No hardcoded base URL/domain literal found in the source. Cannot fetch live data automatically \u2014 verify the domain manually." }); return { ok: false, path: sourcePath, profile, checks, summary: { passed: 0, failed: 1, skipped: 0 } }; }
  let base: URL;
  try { base = new URL(domain); } catch { checks.push({ check: "domain_resolution", ok: false, detail: `"${domain}" is not a valid URL` }); return { ok: false, path: sourcePath, profile, checks, summary: { passed: 0, failed: 1, skipped: 0 } }; }
  const fetched = await fetchPublic(base.toString(), allow_hosts);
  checks.push({ check: "domain_reachable", ok: fetched.ok === true, detail: fetched.ok ? `HTTP ${fetched.status} from ${base.hostname}` : String(fetched.error ?? `HTTP ${fetched.status}`) });
  const body = String(fetched.text ?? "");
  if (fetched.ok) {
    for (const selector of (profile.css_selectors as string[]).slice(0, 25)) {
      const bare = selector.split(/[.\[#:]/)[0].trim();
      const tagOrClassNeedle = selector.replace(/^[.#]/, "");
      const found = bare ? new RegExp(`<${bare}[\\s>]`, "i").test(body) || body.includes(tagOrClassNeedle) : body.includes(tagOrClassNeedle);
      checks.push({ check: `css_selector:${selector}`, ok: found, detail: found ? "Selector text/tag appears in the live response" : "Selector text/tag was not found in the live homepage response \u2014 may only appear on a different page (search/details/chapter), or the site markup may have changed" });
    }
    for (const key of (profile.json_keys as string[]).slice(0, 25)) checks.push({ check: `json_key:${key}`, ok: body.includes(`"${key}"`), detail: body.includes(`"${key}"`) ? "Key literal appears in the live response body" : "Key literal not found on the fetched page \u2014 expected if this key belongs to an API/AJAX endpoint rather than the homepage" });
    for (const attr of (profile.attr_lookups as string[]).slice(0, 15)) checks.push({ check: `attribute:${attr}`, ok: body.includes(`${attr}=`), detail: body.includes(`${attr}=`) ? "Attribute name appears in the live HTML" : "Attribute not found on the fetched page" });
  }
  const passed = checks.filter((c) => c.ok).length, failed = checks.filter((c) => c.ok === false).length;
  return { ok: failed === 0, path: sourcePath, domain_tested: base.toString(), profile, checks, summary: { passed, failed, skipped: 0 }, note: "This is static-analysis-plus-live-fetch, not a real Kotlin execution: it extracts literals from the source and checks whether they still appear in a live anonymous response. A selector/key not found on the homepage may still work correctly on the actual search/details/chapter page the code targets \u2014 review context before concluding the source is broken. It cannot detect logic bugs, only literal drift (renamed fields, moved markup, dead domain)." };
}

const server = new McpServer({ name: "tsuki-plugin-engineering", version: VERSION });
server.tool("tsuki_contract", "Return the bundled Tsuki contract and build requirements.", {}, async () => result({ ok: true, repository: "https://github.com/UsagiApp/Tsuki", version: VERSION, dependency: 'implementation("com.github.UsagiApp:Tsuki:<version>")', build: ["./gradlew test", "./gradlew jar", "d8 --release build/libs/plugin.jar --output plugin.jar"], manga_source: doc(["MangaSource.kt", "api_reference.md"]), manga_parser: doc(["MangaParser.kt", "api_reference.md"]), references: ["skill/references/api_reference.md", "skill/references/research-checklist.md"] }));
server.tool("tsuki_check_dependencies", "Check tools required to research, test, build, and package a Tsuki plugin.", { path: z.string().optional() }, async ({ path }) => { const root = safePath(path ?? "."), checks: RecordValue = {}; for (const command of ["bun", "node", "npm", "java", "git", "d8"]) { const available = commandExists(command); checks[command] = { available }; if (available) { const value = await run(command, command === "java" ? ["-version"] : ["--version"], root, 10000); checks[command] = { available, version: String(value.stdout || value.stderr).trim().split("\n")[0] }; } } checks.gradle_wrapper = existsSync(join(root, "gradlew")) || existsSync(join(root, "gradlew.bat")); checks.android_sdk = Boolean(process.env.ANDROID_HOME || process.env.ANDROID_SDK_ROOT); return result({ ok: true, root, checks }); });
server.tool("tsuki_classify_access", "Classify one or more source capabilities (list/search, details, chapter list, chapter pages, image delivery) as public, authenticated, or paywalled/subscription, using an anonymous fetch plus login-wall and payment-signal detection. Run this before deep research; see references/access-classification.md for the full procedure and manual checks this tool cannot perform (terms of service, robots.txt, region-specific behavior).", { capabilities: z.array(z.object({ name: z.string().describe("Capability label, e.g. 'search', 'details', 'chapter_list', 'chapter_pages:ch12', 'image_delivery'"), url: z.string() })).min(1).max(10), allow_hosts: z.array(z.string()).optional() }, async ({ capabilities, allow_hosts }) => result(await classifyAccess(capabilities as Array<{ name: string; url: string }>, allow_hosts ?? [])));
server.tool("tsuki_fetch_public_source", "Fetch public source material from an explicit safe host allowlist.", { url: z.string(), allow_hosts: z.array(z.string()).optional() }, async ({ url, allow_hosts }) => result(await fetchPublic(url, allow_hosts ?? [])));
server.tool("tsuki_research_source", "Create a structured research report from permitted public URLs and optional fixtures.", { url: z.string(), urls: z.array(z.string()).optional(), allow_hosts: z.array(z.string()).optional(), fixture_dir: z.string().optional(), output_file: z.string().optional() }, async ({ url, urls, allow_hosts, fixture_dir, output_file }) => { const targets = [url, ...(urls ?? [])].slice(0, 20), fetched = []; for (const target of targets) fetched.push(await fetchPublic(target, allow_hosts ?? [])); const root = fixture_dir ? safePath(fixture_dir) : null, fixtures = root && existsSync(root) ? files(root, new Set([".json", ".html", ".htm", ".txt"]), 100).map((file) => ({ file: relative(root, file), bytes: statSync(file).size })) : []; const report = { source: { canonical_url: url, urls: targets }, fetched: fetched.map((x) => ({ url: x.url, ok: x.ok, status: x.status, content_type: x.content_type, preview: String(x.text ?? "").slice(0, 500) })), fixtures, metadata_fields_to_verify: ["title", "alternative_titles", "content_type", "rating", "rating_count", "authors", "status", "cover", "thumbnail", "description", "tags"], filters_to_verify: ["sort", "included_genres", "excluded_genres", "author", "status", "rating", "demographic", "release_year"], chapter_rules: ["oldest_to_newest", "exclude_navigation_entries", "deduplicate"], blockers: fetched.filter((x) => x.ok === false).map((x) => ({ url: x.url, error: x.error })), compliance: "Verify terms, robots.txt, permissions, rate limits, and access boundaries before implementation." }; return result({ ok: true, report, report_file: output_file ? writeReport(output_file, `# Source Research\n\n\`\`\`json\n${JSON.stringify(report, null, 2)}\n\`\`\`\n`) : null }); });
server.tool("tsuki_discover_endpoints", "Inspect permitted fixture text and allowlisted URLs for endpoint patterns.", { urls: z.array(z.string()).optional(), fixture_dir: z.string().optional(), allow_hosts: z.array(z.string()).optional(), include_scripts: z.boolean().optional() }, async ({ urls, fixture_dir, allow_hosts, include_scripts }) => { const sources: { source: string; text: string }[] = []; for (const url of (urls ?? []).slice(0, 20)) { const item = await fetchPublic(url, allow_hosts ?? []); if (item.text) sources.push({ source: url, text: String(item.text) }); } if (fixture_dir) { const root = safePath(fixture_dir); for (const file of files(root, new Set(include_scripts ? [".json", ".html", ".htm", ".js", ".ts"] : [".json", ".html", ".htm", ".txt"]), 100)) sources.push({ source: file, text: text(file) }); } const endpoint = new Set<string>(), graphql = new Set<string>(), pagination = new Set<string>(), images = new Set<string>(), obfuscation = new Set<string>(); for (const item of sources) { for (const m of item.text.matchAll(/https?:\/\/[^\s"'<>]+/g)) endpoint.add(m[0].replace(/[),]}]+$/, "")); for (const m of item.text.matchAll(/(?:\/api\/|graphql|rest\/v?\d*\/)[^\s"'<>]*/gi)) { const value = m[0].replace(/[),]}]+$/, ""); if (/graphql/i.test(value)) graphql.add(value); else endpoint.add(value); } for (const m of item.text.matchAll(/(?:page|offset|limit|cursor|next_page|has_next)[A-Za-z0-9_=-]*/gi)) pagination.add(m[0]); for (const m of item.text.matchAll(/[^\s"'<>]+\.(?:jpg|jpeg|png|webp|avif)(?:\?[^\s"'<>]+)?/gi)) images.add(m[0]); for (const m of item.text.matchAll(/(?:obfuscat|encrypt|decrypt|decode|base64|atob|crypto|signature|signed)/gi)) obfuscation.add(m[0]); } return result({ ok: true, sources: sources.map((x) => x.source), api_endpoints: [...endpoint].slice(0, 200), graphql_endpoints: [...graphql], pagination_patterns: [...pagination], image_patterns: [...images], possible_obfuscation: [...obfuscation], requires_manual_review: obfuscation.size ? ["Review encoding/encryption only through an authorized public mechanism."] : [] }); });
server.tool("tsuki_extract_schema", "Extract JSON paths or HTML hints from a permitted fixture.", { fixture_path: z.string(), kind: z.enum(["search", "details", "chapters", "pages", "filters"]).optional() }, async ({ fixture_path, kind }) => { const path = safePath(fixture_path), source = text(path); if (!source) return fail("Fixture does not exist or is too large", { fixture_path: path }); try { const parsed = JSON.parse(source); return result({ ok: true, fixture_path: path, kind: kind ?? "unknown", format: "json", paths: paths(parsed), sample_strings: strings(parsed).slice(0, 100), missing_required_fields: [] }); } catch { return result({ ok: true, fixture_path: path, kind: kind ?? "unknown", format: "html", selector_hints: [...source.matchAll(/(?:id|class|data-[\w-]+)=["'][^"']+["']/gi)].map((m) => m[0]).slice(0, 200), links: [...source.matchAll(/href=["']([^"']+)["']/gi)].map((m) => m[1]).slice(0, 200), missing_required_fields: [] }); } });
server.tool("tsuki_analyze_filters", "Analyze filter options from JSON or HTML fixtures and report Tsuki mapping candidates.", { fixture_path: z.string(), api_response_path: z.string().optional() }, async ({ fixture_path, api_response_path }) => { const pathsIn = [fixture_path, ...(api_response_path ? [api_response_path] : [])].map(safePath), source = pathsIn.map(text).join("\n"), lower = `${source}\n${pathsIn.map((p) => { try { return strings(jsonFile(p)).join(" "); } catch { return text(p); } }).join(" ")}`.toLowerCase(); const detected = { sort_orders: /sort|popular|rating|latest|newest|updated|alphabet/.test(lower), genres: /genre|category|tag/.test(lower), statuses: /status|ongoing|completed|finished/.test(lower), authors: /author|artist|creator/.test(lower), years: /year|released|publication/.test(lower), ratings: /rating|score|star/.test(lower), demographics: /demographic|audience|shounen|seinen|josei|shoujo/.test(lower) }; return result({ ok: true, fixtures: pathsIn, detected, mapping_candidates: Object.entries(detected).filter(([, value]) => value).map(([key]) => key), unsupported_by_tsuki: [], note: "Confirm each filter against the source UI/API before implementing." }); });
server.tool("tsuki_extract_pages", "Extract candidate page image URLs from a permitted HTML or JSON fixture, including lazy-loading and srcset attributes.", { fixture_path: z.string() }, async ({ fixture_path }) => { const path = safePath(fixture_path), source = text(path); if (!source) return fail("Fixture does not exist or is too large", { fixture_path: path }); return result({ ok: true, fixture_path: path, candidates: extractPageCandidates(source), note: "Review candidates and remove placeholders, ads, thumbnails, and unrelated images before using them." }); });
server.tool("tsuki_validate_pages", "Validate page records for completeness, ordering, duplicates, placeholders, and gaps.", { pages: z.array(z.unknown()).optional(), fixture_path: z.string().optional(), expected_count: z.number().int().positive().optional() }, async ({ pages, fixture_path, expected_count }) => { let input: unknown = pages; if (fixture_path) { try { input = jsonFile(safePath(fixture_path)); } catch (error) { return fail(`Could not read page fixture: ${String(error)}`); } } return result(await validatePageRecords(input, expected_count)); });
server.tool("tsuki_check_image_urls", "Check the structure of page image URLs without downloading protected content.", { urls: z.array(z.string()), allow_hosts: z.array(z.string()).optional() }, async ({ urls, allow_hosts }) => { const checks = urls.slice(0, 500).map((url) => ({ url, public_https: publicHttps(url), allowlisted: allowed(url, allow_hosts ?? []), likely_image: /\.(?:jpg|jpeg|png|webp|avif|gif)(?:\?|$)/i.test(url), has_query_token: /(?:token|sig|signature|expires|auth)=/i.test(url) })); return result({ ok: checks.every((x) => x.public_https && x.allowlisted), checks, note: "A structurally valid URL is not proof that an image is accessible; validate status and MIME only through an authorized, rate-limited request." }); });
server.tool("tsuki_compare_page_counts", "Compare page records or page-count snapshots and report missing or added pages.", { before_pages: z.array(z.unknown()).optional(), after_pages: z.array(z.unknown()).optional(), before_fixture: z.string().optional(), after_fixture: z.string().optional() }, async ({ before_pages, after_pages, before_fixture, after_fixture }) => { const read = (items: unknown[] | undefined, fixture: string | undefined) => { if (items) return items; if (!fixture) return []; try { const value = jsonFile(safePath(fixture)); return Array.isArray(value) ? value : Array.isArray((value as RecordValue).pages) ? (value as RecordValue).pages as unknown[] : []; } catch { return []; } }; const before = read(before_pages, before_fixture), after = read(after_pages, after_fixture); const key = (item: unknown, index: number) => typeof item === "string" ? item : String((item as RecordValue)?.url ?? (item as RecordValue)?.src ?? (item as RecordValue)?.index ?? index); const beforeKeys = before.map(key), afterKeys = after.map(key); return result({ ok: beforeKeys.length === afterKeys.length && beforeKeys.every((value, index) => value === afterKeys[index]), before_count: beforeKeys.length, after_count: afterKeys.length, missing_from_after: beforeKeys.filter((value) => !afterKeys.includes(value)), added_in_after: afterKeys.filter((value) => !beforeKeys.includes(value)), order_changed: beforeKeys.length === afterKeys.length && beforeKeys.some((value, index) => value !== afterKeys[index]) }); });
server.tool("tsuki_normalize_chapters", "Normalize chapters oldest-to-newest and remove navigation, non-chapter, and duplicate entries.", { chapters: z.array(z.unknown()).optional(), fixture_path: z.string().optional(), output_file: z.string().optional() }, async ({ chapters, fixture_path, output_file }) => { let input: unknown = chapters; if (fixture_path) { try { input = jsonFile(safePath(fixture_path)); } catch (error) { return fail(`Could not read chapter fixture: ${String(error)}`); } } const normalized = normalize(input); return result({ ok: true, ...normalized, output_file: output_file ? writeReport(output_file, JSON.stringify(normalized, null, 2) + "\n") : null }); });
server.tool("tsuki_inspect_plugin", "Inspect Kotlin files for Tsuki methods, metadata, filters, ordering, and risky patterns.", { path: z.string() }, async ({ path }) => { const root = safePath(path); return existsSync(root) ? result({ ok: true, ...inspection(root) }) : fail("Directory does not exist"); });
server.tool("tsuki_validate_plugin", "Validate a plugin against structural and required Tsuki quality rules.", { path: z.string(), strict: z.boolean().optional() }, async ({ path, strict }) => { const root = safePath(path); if (!existsSync(root)) return fail("Directory does not exist"); const inspected = inspection(root), all = files(root, new Set([".kt", ".kts", ".md", ".json"])).map(text).join("\n"), errors: RecordValue[] = [], rules: [RegExp, string][] = [[/oldest|ascending|sortedBy|sortedWith|compareBy|reversed/i, "chapter ordering evidence"], [/Read from beginning|Read latest|readFromBeginning|readLatest/i, "navigation-entry exclusion evidence"], [/dedup|distinctBy|duplicate/i, "chapter deduplication evidence"], [/test|assert|shouldBe|junit/i, "fixture/test evidence"]]; for (const [pattern, message] of rules) if (!pattern.test(all)) errors.push({ code: message.toUpperCase().replace(/[^A-Z]+/g, "_"), message: `Missing ${message}` }); const warnings = (inspected.findings as RecordValue[]).filter((x) => x.severity === "warning" && x.present); return result({ ok: errors.length === 0, errors, warnings, inspection: inspected, strict: Boolean(strict) }); });
server.tool("tsuki_test_source_live", "Test an existing Tsuki source .kt file against its live domain WITHOUT installing, building, or modifying the plugin. Statically extracts the hardcoded domain, CSS selectors, JSON keys, and attribute lookups from the Kotlin file, then fetches the live domain anonymously and checks whether each literal still appears in the response. Reports per-check pass/fail with evidence. This never edits the source file \u2014 use tsuki_inspect_plugin/tsuki_validate_plugin for structural code checks, and treat any failing check as a lead to investigate, not a confirmed bug, since a selector may legitimately live on a different page than the one fetched here.", { source: z.string().describe("Path to the .kt file, or a source/class name to search for under the current directory"), allow_hosts: z.array(z.string()).optional().describe("Additional hosts to allow fetching from, beyond the source's own detected domain") }, async ({ source, allow_hosts }) => { const resolved = resolveSourceFile(source); if (resolved.error) return fail(resolved.error); const domainHint = (() => { try { const body = text(resolved.path); const match = body.match(/(?:BASE_URL|baseUrl|domain)\s*[=:]\s*"(https?:\/\/[^"]+)"/i) ?? body.match(/"(https?:\/\/[^"\s]+)"/); return match ? new URL(match[1]).hostname : null; } catch { return null; } })(); const hosts = [...(allow_hosts ?? []), ...(domainHint ? [domainHint] : [])]; return result(await liveTestSource(resolved.path, hosts)); });
server.tool("tsuki_mark_source_broken", "Mark a Tsuki source as broken/dead in its own file, for sources that tsuki_test_source_live and manual review confirm cannot be fixed (typically total site shutdown, domain no longer resolving, or the entire reading path now requires payment/login). Inserts a clearly delimited KDoc block and a runtime marker comment directly above the class declaration; does not remove or rewrite any existing parsing logic, and does not touch build files or source-list registries.", { source: z.string().describe("Path to the .kt file, or a source/class name to search for under the current directory"), reason: z.string().describe("Why the source is considered broken/unfixable, e.g. 'Domain no longer resolves (checked 2026-09-16); site appears permanently shut down.'"), evidence_file: z.string().optional().describe("Optional path to a tsuki_test_source_live JSON report to reference for evidence") }, async ({ source, reason, evidence_file }) => { const resolved = resolveSourceFile(source); if (resolved.error) return fail(resolved.error); const body = text(resolved.path); if (!body) return fail("Could not read source file", { path: resolved.path }); if (/@Broken|BROKEN_SOURCE_MARKER/.test(body)) return fail("Source already marked as broken; edit the existing marker manually if the reason changed.", { path: resolved.path }); const classMatch = body.match(/\n(class\s+\w+\s*:\s*[\w.]+\([\s\S]*?\)\s*\{)/) ?? body.match(/\n(class\s+\w+[\s\S]*?\{)/); if (!classMatch) return fail("Could not locate a class declaration to annotate. Add the broken-source marker manually.", { path: resolved.path }); const today = new Date().toISOString().slice(0, 10); const marker = `\n/**\n * BROKEN_SOURCE_MARKER (added ${today})\n * This source is marked broken and is not expected to return working results.\n * Reason: ${reason.replace(/\*\//g, "*\\/")}\n${evidence_file ? ` * Evidence: ${evidence_file}\n` : ""} * Parsing logic below is left intact for reference and possible future repair;\n * it has not been removed. Do not re-enable this source without re-running\n * tsuki_test_source_live and clearing this marker.\n */\n@Deprecated("Source marked broken: ${reason.replace(/"/g, "'").slice(0, 200)}")\n${classMatch[1]}`; const updated = body.replace(classMatch[0], marker); writeFileSync(resolved.path, updated, "utf8"); return result({ ok: true, path: resolved.path, marked: true, reason, evidence_file: evidence_file ?? null }); });
server.tool("tsuki_scaffold_plugin", "Generate a review-required Kotlin scaffold for a permitted source.", { package_name: z.string(), source_name: z.string(), domain: z.string(), output_dir: z.string().optional() }, async ({ package_name, source_name, domain, output_dir }) => { if (!/^[A-Za-z][\w.]*$/.test(package_name) || !/^[A-Za-z][\w-]*$/.test(source_name)) return fail("Invalid package_name or source_name"); let parsed: URL; try { parsed = new URL(domain.includes("://") ? domain : `https://${domain}`); } catch { return fail("Invalid domain"); } if (parsed.protocol !== "https:" || !parsed.hostname) return fail("domain must be HTTPS"); const out = resolve(output_dir ?? "./generated-tsuki-plugin"), packageDir = join(out, "src/main/kotlin", ...package_name.split(".")); mkdirSync(packageDir, { recursive: true }); const sourceFile = join(packageDir, `${source_name}.kt`); writeFileSync(sourceFile, `package ${package_name}\n\nimport tsuki.core.PagedMangaParser\nimport tsuki.model.*\n\n/** Review terms, rate limits, selectors, and API permission before shipping. */\nclass ${source_name} : PagedMangaParser(Source) {\n    override suspend fun getList(offset: Int, order: SortOrder, filter: MangaListFilter): List<Manga> = emptyList()\n    override suspend fun getDetails(manga: Manga): Manga = manga\n    override suspend fun getPages(chapter: MangaChapter): List<MangaPage> = emptyList()\n    override suspend fun getPageUrl(page: MangaPage): String = page.url\n\n    private object Source : MangaSource {\n        override val name = "${source_name}"\n        override val locale = "en"\n        override val contentType = ContentType.MANGA\n    }\n}\n`); const review = join(out, "REVIEW.md"); writeFileSync(review, "# Generated Tsuki plugin scaffold\n\nAdd complete metadata, site-supported filters, oldest-to-newest chapter ordering, navigation-entry exclusion, fixtures, tests, and compliance review before shipping.\n"); return result({ ok: true, source_file: sourceFile, review_file: review }); });
server.tool("tsuki_generate_plugin", "Generate a scaffold plus fixtures, tests, and a review report.", { package_name: z.string(), source_name: z.string(), domain: z.string(), output_dir: z.string().optional() }, async ({ package_name, source_name, domain, output_dir }) => { const out = resolve(output_dir ?? "./generated-tsuki-plugin"); const scaffold = await (async () => { if (!/^[A-Za-z][\w.]*$/.test(package_name) || !/^[A-Za-z][\w-]*$/.test(source_name)) return null; const parsed = new URL(domain.includes("://") ? domain : `https://${domain}`); if (parsed.protocol !== "https:") return null; const packageDir = join(out, "src/main/kotlin", ...package_name.split(".")); mkdirSync(packageDir, { recursive: true }); const sourceFile = join(packageDir, `${source_name}.kt`); writeFileSync(sourceFile, `package ${package_name}\n\nimport tsuki.core.PagedMangaParser\nimport tsuki.model.*\n\nclass ${source_name} : PagedMangaParser(Source) {\n    override suspend fun getList(offset: Int, order: SortOrder, filter: MangaListFilter): List<Manga> = emptyList()\n    override suspend fun getDetails(manga: Manga): Manga = manga\n    override suspend fun getPages(chapter: MangaChapter): List<MangaPage> = emptyList()\n    override suspend fun getPageUrl(page: MangaPage): String = page.url\n    private object Source : MangaSource { override val name = "${source_name}"; override val locale = "en"; override val contentType = ContentType.MANGA }\n}\n`); return sourceFile; })(); if (!scaffold) return fail("Invalid package_name, source_name, or domain"); const fixtureDir = join(out, "src/test/resources/fixtures"); mkdirSync(fixtureDir, { recursive: true }); for (const kind of ["search", "details", "chapters", "pages", "filters"]) writeFileSync(join(fixtureDir, `${kind}.json`), JSON.stringify({ fixture: kind, TODO: "Replace with a permitted captured response" }, null, 2) + "\n"); const testDir = join(out, "src/test/kotlin"); mkdirSync(testDir, { recursive: true }); const testFile = join(testDir, `${source_name}ContractTest.kt`); writeFileSync(testFile, "// TODO: Add metadata, filters, chapter ordering, navigation exclusion, deduplication, pagination, and image URL tests.\n"); const review = join(out, "REVIEW.md"); writeFileSync(review, "# Generated Tsuki plugin review\n\nComplete research, metadata, filters, tests, chapter ordering, compliance, and build verification before shipping.\n"); return result({ ok: true, source_file: scaffold, fixture_dir: fixtureDir, test_file: testFile, review_file: review }); });
server.tool("tsuki_generate_fixtures", "Generate fixture templates for source parser tests.", { source_dir: z.string(), fixture_types: z.array(z.enum(["search", "details", "chapters", "pages", "filters"])).optional() }, async ({ source_dir, fixture_types }) => { const root = safePath(source_dir), dir = join(root, "src/test/resources/fixtures"); mkdirSync(dir, { recursive: true }); const output: string[] = []; for (const kind of fixture_types ?? ["search", "details", "chapters", "pages", "filters"]) { const file = join(dir, `${kind}.json`); if (!existsSync(file)) writeFileSync(file, JSON.stringify({ fixture: kind, TODO: "Replace with a permitted captured response" }, null, 2) + "\n"); output.push(file); } return result({ ok: true, files: output }); });
server.tool("tsuki_generate_tests", "Generate a Kotlin test checklist file for metadata, filters, and chapter rules.", { source_dir: z.string(), source_class: z.string().optional() }, async ({ source_dir, source_class }) => { const root = safePath(source_dir), dir = join(root, "src/test/kotlin"); mkdirSync(dir, { recursive: true }); const file = join(dir, `${source_class ?? "Source"}ContractTest.kt`); if (!existsSync(file)) writeFileSync(file, "// TODO: Add metadata, supported filters, oldest-to-newest chapters, navigation exclusion, duplicate removal, pagination, and image URL tests.\n"); return result({ ok: true, test_file: file }); });
server.tool("tsuki_test_plugin", "Run the plugin test task and return structured output.", { path: z.string(), task: z.string().optional() }, async ({ path, task }) => { const root = safePath(path), gradle = existsSync(join(root, "gradlew")) ? "./gradlew" : existsSync(join(root, "gradlew.bat")) ? "gradlew.bat" : null; return gradle ? result(await run(gradle, [task ?? "test", "--no-daemon"], root, 300000)) : fail("No Gradle wrapper found", { path: root }); });
server.tool("tsuki_build_plugin", "Run Gradle tests/JAR build and optionally dex the artifact.", { path: z.string(), dex: z.boolean().optional(), clean: z.boolean().optional() }, async ({ path, dex, clean }) => { const root = safePath(path), gradle = existsSync(join(root, "gradlew")) ? "./gradlew" : existsSync(join(root, "gradlew.bat")) ? "gradlew.bat" : null; if (!gradle) return fail("No Gradle wrapper found", { path: root }); const commands: RecordValue[] = []; if (clean) commands.push(await run(gradle, ["clean", "--no-daemon"], root, 300000)); commands.push(await run(gradle, ["test", "jar", "--no-daemon"], root, 300000)); let dexResult: RecordValue | null = null; if (dex) { const jar = join(root, "build/libs/plugin.jar"); dexResult = existsSync(jar) && commandExists("d8") ? await run("d8", ["--release", jar, "--output", join(root, "plugin.jar")], root, 120000) : { ok: false, error: "plugin.jar or d8 was not found" }; } return result({ ok: commands.every((x) => x.ok) && (!dex || Boolean(dexResult?.ok)), commands, dex: dexResult, artifacts: files(root, new Set([".jar", ".dex"]), 50).map((x) => relative(root, x)) }); });
server.tool("tsuki_inspect_artifact", "Inspect JAR/DEX artifacts for presence, size, and class names.", { path: z.string() }, async ({ path }) => { const root = safePath(path), artifacts = files(root, new Set([".jar", ".dex"]), 100).map((file) => ({ file: relative(root, file), bytes: statSync(file).size })), classes: string[] = []; for (const artifact of artifacts.filter((x) => x.file.endsWith(".jar"))) { const listing = await run("jar", ["tf", join(root, artifact.file)], root, 30000); if (listing.ok) classes.push(...String(listing.stdout).split("\n").filter((x) => /\.class$/.test(x)).slice(0, 500)); } return result({ ok: true, artifacts, class_names: classes, has_tsuki_source: classes.some((x) => /Manga(Source|Parser)/i.test(x)) }); });
server.tool("tsuki_compare_source_versions", "Compare two fixture directories or files.", { before_path: z.string(), after_path: z.string() }, async ({ before_path, after_path }) => { const readTree = (input: string) => { const root = safePath(input), map = new Map<string, string>(); if (existsSync(root) && statSync(root).isDirectory()) for (const file of files(root, new Set([".json", ".html", ".htm", ".txt", ".js", ".ts"]), 500)) map.set(relative(root, file), text(file)); else map.set(basename(root), text(root)); return map; }; const before = readTree(before_path), after = readTree(after_path), added = [...after.keys()].filter((x) => !before.has(x)), removed = [...before.keys()].filter((x) => !after.has(x)), changed = [...after.keys()].filter((x) => before.has(x) && before.get(x) !== after.get(x)).map((file) => ({ file, before_bytes: Buffer.byteLength(before.get(file) ?? ""), after_bytes: Buffer.byteLength(after.get(file) ?? "") })); return result({ ok: true, added, removed, changed, breaking_changes: [...removed, ...changed.map((x) => x.file)] }); });
server.tool("tsuki_create_source_report", "Create a Markdown source report from JSON research, validation, test, and build results.", { output_file: z.string(), title: z.string().optional(), input_files: z.array(z.string()).optional() }, async ({ output_file, title, input_files }) => { const sections = (input_files ?? []).map((file) => `## ${basename(file)}\n\n\`\`\`json\n${text(safePath(file)).slice(0, 100000)}\n\`\`\``).join("\n\n"); return result({ ok: true, report_file: writeReport(output_file, `# ${title ?? "Tsuki Source Report"}\n\nGenerated by tsuki-plugin-engineering.\n\n${sections || "No input reports supplied."}\n\n## Maintenance\n\nRe-run research and fixture comparison when the source changes.\n`) }); });

async function main() { await server.connect(new StdioServerTransport()); }
main().catch((error) => { console.error("Fatal:", error); process.exit(1); });
